/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Vertx JUnit5 for testing.
    // testImplementation("io.vertx:vertx-junit5:4.4.4")

    // testRuntimeOnly("io.vertx:vertx-junit5:4.4.4")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    // Vertx Core Http dependency I guess is already on the Vertx Web package though not sure so retain
    compile("io.vertx:vertx-core:4.4.4")

    // Vertx Web dependency
    compile("io.vertx:vertx-web:4.4.4")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("app.App")
}

// tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
   //  useJUnitPlatform()
// }
