/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import io.smallrye.mutiny.Uni;

public class App {

    public static void main(String[] args) {
	    Uni.createFrom().item(1)
		    .onItem().transform(i -> "hello-" + i)
		    .onItem().delay().by(Duration.ofMillis(100))
		    .subscribe().with(System.out::println);
    }
}
